"""Task creation and status endpoints."""

from uuid import uuid4

from fastapi import APIRouter, HTTPException, Request

from ..agent.state import TaskState, TaskStatus
from ..procurement.schemas import ProcurementRecommendation, ProcurementRequest

router = APIRouter(tags=["tasks"])


def _task_state(request: Request, task_id: str) -> TaskState:
    repository = request.app.state.repository
    record = repository.get(task_id)
    if record is None:
        raise HTTPException(status_code=404, detail="Task not found")
    return repository.to_state(record)


@router.post("", response_model=TaskState, status_code=201)
async def create_task(payload: ProcurementRequest, request: Request) -> TaskState:
    """Create a procurement task and execute it to its next stable state."""

    repository = request.app.state.repository
    orchestrator = request.app.state.orchestrator
    task_id = uuid4().hex
    repository.create(task_id, payload)
    return await orchestrator.run(task_id, payload)


@router.get("/{task_id}", response_model=TaskState)
async def get_task(task_id: str, request: Request) -> TaskState:
    """Return the current checkpoint state of a task."""

    return _task_state(request, task_id)


@router.get("/{task_id}/result", response_model=ProcurementRecommendation)
async def get_task_result(task_id: str, request: Request) -> ProcurementRecommendation:
    """Return the recommendation generated by a task."""

    repository = request.app.state.repository
    if repository.get(task_id) is None:
        raise HTTPException(status_code=404, detail="Task not found")
    recommendation = repository.get_recommendation(task_id)
    if recommendation is None:
        raise HTTPException(status_code=409, detail="Recommendation is not ready")
    return recommendation


@router.post("/{task_id}/resume", response_model=TaskState)
async def resume_task(task_id: str, request: Request) -> TaskState:
    """Resume a FAILED task using its original plan and checkpoint."""

    repository = request.app.state.repository
    orchestrator = request.app.state.orchestrator
    record = repository.get(task_id)
    if record is None:
        raise HTTPException(status_code=404, detail="Task not found")
    state = repository.to_state(record)
    if state.status == TaskStatus.COMPLETED:
        raise HTTPException(status_code=409, detail="Completed tasks cannot be resumed")
    if state.status == TaskStatus.WAITING_APPROVAL:
        raise HTTPException(
            status_code=409,
            detail="Waiting-approval tasks must be approved, not resumed",
        )
    if state.status != TaskStatus.FAILED:
        raise HTTPException(status_code=409, detail=f"Cannot resume from {state.status.value}")
    return await orchestrator.resume(task_id)


@router.get("/{task_id}/trace")
async def get_task_trace(task_id: str, request: Request) -> list[dict]:
    """Return persistent execution trace rows for a task."""

    repository = request.app.state.repository
    if repository.get(task_id) is None:
        raise HTTPException(status_code=404, detail="Task not found")
    rows = repository.list_trace(task_id)
    return [
        {
            "task_id": row.task_id,
            "step_name": row.step_name,
            "component": row.component,
            "action": row.action,
            "status": row.status,
            "duration_ms": row.duration_ms,
            "attempt": row.attempt,
            "error": row.error,
            "model": row.model,
            "token_input": row.token_input,
            "token_output": row.token_output,
            "created_at": row.created_at.isoformat(),
        }
        for row in rows
    ]
